[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  VITE_AUTH0_DOMAIN = "dev-d1hv17m7xpy4f4dt.us.auth0.com"
  VITE_AUTH0_CLIENT_ID = "7Ms8Fy4UviPrL8kLYqiLFUT25Jc3DA8o"
